[package]
name = "libthread_db"
version = "0.1.0"
authors = ["Lukas Werling <lukas.werling@gmail.com>"]
edition = "2018"

[dependencies]
dlopen = "0.1"
dlopen_derive = "0.1"
libc = "0.2"
errno = "0.2"
goblin = "0.0.19"
proc-maps = "0.1.5"
nix = "0.13"
